# Generated by Django 6.1 on 2026-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criancas', '0002_crianca_terapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='criancas/'),
        ),
    ]
