# Generated by Django 6.1 on 2026-08-17 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('pergunta_aberta', 'Pergunta Aberta'), ('jogo_palavras', 'Jogo de Palavras')], max_length=20)),
                ('enunciado', models.TextField()),
                ('configuracao', models.JSONField(blank=True, default=dict)),
                ('sessao_modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessoes.sessaomodelo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sessao_modelo', 'numero'), name='numero_unico_por_sessao')],
            },
        ),
    ]
