# Generated by Django 6.1 on 2026-08-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_exercicioresultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciomodelo',
            name='tipo',
            field=models.CharField(choices=[('pergunta_aberta', 'Pergunta Aberta'), ('jogo_palavras', 'Jogo de Palavras'), ('multipla_escolha', 'Múltipla Escolha'), ('verdadeiro_falso', 'Verdadeiro ou Falso')], max_length=20),
        ),
    ]
