# Generated by Django 6.1 on 2026-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_alter_exerciciomodelo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciomodelo',
            name='tipo',
            field=models.CharField(choices=[('pergunta_aberta', 'Pergunta Aberta'), ('jogo_palavras', 'Jogo de Palavras'), ('multipla_escolha', 'Múltipla Escolha'), ('verdadeiro_falso', 'Verdadeiro ou Falso'), ('caca_palavras', 'Caça-Palavras'), ('cruzadinha', 'Cruzadinha'), ('ordena_letras', 'Ordene as Letras'), ('preenche_lacunas_letras', 'Lacunas com Letras')], max_length=30),
        ),
    ]
