# Generated by Django 6.1 on 2026-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0004_alter_exerciciomodelo_tipo'),
        ('sessoes', '0002_sessaorealizada'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercicioresultado',
            constraint=models.UniqueConstraint(fields=('sessao_realizada', 'exercicio_modelo'), name='resultado_unico_por_exercicio_sessao'),
        ),
    ]
