# Generated by Django 6.1 on 2026-09-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0005_exercicioresultado_resultado_unico_por_exercicio_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicioresultado',
            name='respostas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
