# Generated by Django 6.1 on 2026-08-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
