# Generated by Django 6.1 on 2026-08-27 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0002_sessaorealizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(blank=True, default='#4F46E5', help_text='Código de cor (HEX) para identificação visual', max_length=20)),
                ('icone', models.CharField(blank=True, default='bi-stars', help_text='Classe de ícone Bootstrap', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='sessaomodelo',
            options={'ordering': ['numero'], 'verbose_name': 'Sessão Modelo', 'verbose_name_plural': 'Sessões Modelo'},
        ),
        migrations.AddField(
            model_name='sessaomodelo',
            name='faixa_etaria',
            field=models.CharField(blank=True, default='Geral', help_text='Faixa etária recomendada (ex: 3 a 5 anos, 6 a 10 anos, 11+ anos)', max_length=50),
        ),
        migrations.AddField(
            model_name='sessaomodelo',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Objetivo pedagógico e terapêutico da sessão'),
        ),
        migrations.AlterField(
            model_name='sessaomodelo',
            name='titulo',
            field=models.CharField(help_text='Nomenclatura da sessão', max_length=100),
        ),
        migrations.AddField(
            model_name='sessaomodelo',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_modelo', to='sessoes.tema'),
        ),
    ]
