# Generated by Django 6.1 on 2026-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0005_exercicioresultado_resultado_unico_por_exercicio_sessao'),
        ('sessoes', '0003_tema_alter_sessaomodelo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaorealizada',
            name='exercicios_selecionados',
            field=models.ManyToManyField(blank=True, to='exercicios.exerciciomodelo'),
        ),
    ]
